### ISSUE TITLE
Question About run_witth_tc.sh line 27. 'docker exec -d -w /app/tc_profiles alphartc_pyinfer bash ./tc_policy.sh $PROFILE'

### ISSUE THREAD

**Issue by dudulu214319** [NUStreaming/BoB#4]
Hello, I want to use the tc script, but the ./tc_policy.sh in this command is not seen in the project. Do I need to complete it myself? Very looking forward to your answer.

**Comment by Jadaeu** [comment]
您好！我是一名研二在读生，最近一直在跑BoB源码，但一直没跑成功。请问BoB源码您跑出来结果了吗？它的结果是什么样的？

**Comment by dudulu214319** [comment]
Sorry, I have been busy with some other projects recently so I haven't been able to run through the source code of BoB yet. I may continue to study it when I have time~

**Comment by Jadaeu** [comment]
> 对不起，我最近一直在忙于其他一些项目，所以我还无法运行BoB的源代码。有时间可能会继续学习~

嗯嗯好的，谢谢
